version: '3.7'

services:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'opentracing_demo_db1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'opentracing'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'opentracing'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'opentracing'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql

  springboot:
    image: opentracing-demo-springboot:latest
    restart: always
    depends_on:
      - db
    ports:
      # <Port exposed> : < Tomcat port running inside container>
      - '5000:8085'
    expose:
      # Opens port 5000 on the container
      - '5000'

  aspnetcore:
    image: opentracing-demo-aspnetcore:latest
    restart: always
    depends_on:
      - db
    ports:
      # <Port exposed> : < Tomcat port running inside container>
      - '5001:80'
    expose:
      # Opens port 5001 on the container
      - '5001'

# Names our volume
volumes:
  my-db:
