version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'opentracing_demo_db1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'opentracing'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'opentracing'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'opentracing'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
